name: Daily Airing Check

on:
  schedule:
    - cron: '0 3 * * *'  # 06:00 за Києвом (03:00 UTC)
  workflow_dispatch:  # Дозволяє ручний запуск

jobs:
  airing-check:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      # Клонуємо ПРИВАТНИЙ репозиторій з кодом
      - name: Checkout private code repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO_NAME }}  # Наприклад: username/main_parser
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: code
      
      # Встановлюємо Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      # Встановлюємо залежності
      - name: Install dependencies
        working-directory: code
        run: |
          python -m pip install --upgrade pip
          pip install -r new_parsers/requirements.txt
      
      # Запускаємо airing парсер
      - name: Run airing parser
        working-directory: code
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TELEGRAM_ANIME_BOT_TOKEN: ${{ secrets.TELEGRAM_ANIME_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PARSER_PROXY: ${{ secrets.PARSER_PROXY }}
        run: |
          echo "Запуск Daily Airing Check"
          python -m new_parsers.runImports airing
      
      # Повідомлення про помилку
      - name: Notify on failure
        if: failure()
        env:
          TELEGRAM_ANIME_BOT_TOKEN: ${{ secrets.TELEGRAM_ANIME_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -X POST "https://api.telegram.org/bot${TELEGRAM_ANIME_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="_Сталася помилка в Daily Airing Check_" \
            -d parse_mode="MarkdownV2"

